config/routes.rb
Rails.application.routes.draw do
    resources :author
    resources :book
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'homepage#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :comments
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    has_many :comments
    has_many :tagings
    has_many :tags, through: :tagings

    def tag_list
        tags.each do |tag|
            tag.name
        end.join(", ")
    end

    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tagings
    has_many :books, through: :tagings

    def to_s
        name
    end
end

app/models/taging.rb
class Taging < ApplicationRecord
    belongs_to :tag
    belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    
    def index
        @author=Author.all
    end

    def edit
    end

    def new 
    end

    def show
        @author=Author.find(params[:id])
    end

    def destroy
    end

    def update
    end

    def create
    end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
    def index
        @book=Book.all
    end

    def new
        @book=Book.new 
        # binding.pry
    end

    def edit
    end
    
    def show 
        @book=Author.find(params[:author_id]).books
    end

    def create
        @book=Book.new(get_params)
        if @book.save
            flash[:notice]="Book saved Successfully"
            redirect_to @book
        else
            render :new, status: :unprocessable_entity

        end
    end


    def destroy
    end

    def update
    end

   

    private

    def get_params
        params.require(:book).permit(:name, :descr, :author_id)
    end
    

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/author/index.html.erb
  <div class="container" style="margin-top:20px;" >
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.png') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      BOOK APP
    </a>
    <%#= link_to "Create New TODO", new_todo_path, {class: "btn btn-outline-primary"} %>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>
<div class="container" >
<% @author.each do |auth|%>
<div class="card text-center"style="margin-top:20px;" >
  <div class="card-header">
 <h5 class="card-title"><%= link_to auth.name.upcase, author_path(auth.id) %></h5>
  </div>
  <div class="card-body">
    <p class="card-text"><strong>Location:</strong> <%=auth.location %></p>
    <p class="card-text">Has <%= auth.books.count %> Book/s <%=link_to "View", book_path(auth.id), {class: "btn btn-outline-primary"}  %></p>
  </div>

</div>

<% end%>

</div>

  </div>

app/views/author/show.html.erb
<div class="container" style="margin-top:20px;" >
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.png') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      BOOK APP
    </a>
    <%= link_to "Add new Book", new_book_path, {class: "btn btn-outline-primary"} %>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>

<div class="container" >
<div class="text-center">
  <img src="<%= asset_url('book1.jpg') %>" alt="crypt">
  <div class="card-body" style="margin-top:20px;">
    <h5 class="card-title"><%= @author.name.upcase%></h5>
    <p class="card-text">Description about author comes here. Currently that field is not available.</p>
    <a href="<%= book_path(@author) %>" class="btn btn-primary position-relative">View Books
    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
    <%= @author.books.count%>
    <span class="visually-hidden">Books</span>
  </span>
  </a>
  </div>
</div>


</div>
</div>

app/views/book/_form.html.erb
<% if @book.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= pluralize(@book.errors.count, "error") %> prohibited this todo from being saved:!</h4>
    <ul>
        <% @book.errors.each do |error| %>
          <li class="mb-0"><%= error.full_message %></li>
        <% end %>
      </ul>
    <hr>
  <p class="mb-0">Please check and give proper inputs.</p>
</div>
    
  <% end %>

<%= form_with(model: @book, url: book_index_path) do |b| %>
<div class="mb-3 row">
    <%= b.label :name, "Name",{class:"form-label"} %>
    <%= b.text_field :name, {class:"form-control", placeholder:"Enter name...", required: "true"} %>
</div>

<div class="mb-3 row">
    <%= b.label :descr, "Description",{class:"form-label"} %>
    <%= b.text_area :descr, {class:"form-control", placeholder:"Enter Book description...", required: "true"} %>
</div>


<div class="mb-3 row">
    <%= b.label :author_id, "Author id",{class:"form-label"} %>
    <%= b.text_field :author_id, {class:"form-control", placeholder:"Enter Author id...",type:"number", required: "true"} %>
</div>

<div class="mb-3 row">
<center>
    <%=b.submit(class:"btn btn-primary mb-3")%>
    </center>
</div>

<% end %>

app/views/book/new.html.erb
  <div class="container" style="margin-top:20px;" >
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.png') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      BOOK APP
    </a>
    <%#= link_to "Create New TODO", new_todo_path, {class: "btn btn-outline-primary"} %>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>
<div class="container" >
<%= render 'form'%>

</div>

  </div>

app/views/book/show.html.erb
<div class="container" style="margin-top:20px;" >
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.png') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      BOOK APP
    </a>
    <%#= link_to "Create New Book", new_book_path, {class: "btn btn-outline-primary"} %>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>

<div class="container" >
<% @book.each do |b|%>
<div class="card text-center"style="margin-top:20px;" >
  <div class="card-header">
 <h5 class="card-title"><%= b.name.upcase%></h5>
  </div>
  <div class="card-body">
    <p class="card-text"><strong>Description:</strong> <%=b.descr %></p>
  </div>

</div>

<% end%>

</div>

</div>

app/views/homepage/home.html.erb
 <div class="container" style="margin-top:20px;" >
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.png') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      BOOKS
    </a>
    <%= link_to "Get Started", author_index_path, {class: "btn btn-outline-success"} %>

  </div>
</nav>
    <div class="jumbotron" >
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= asset_url('book1.jpg') %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= asset_url('book2.jpg') %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= asset_url('book3.jpg') %>" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  
</div>
  </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
  
</html>